### ISSUE TITLE
when sending lots of messages nlohmann::json error occurs

### ISSUE THREAD

**Issue by niansa** [DiscordPP/rest-beast#8]
![dppbug](https://user-images.githubusercontent.com/20720267/105180916-720b5a00-5b2b-11eb-8d1a-566080b3a9e8.png)

plugin-ratelimit.hh line 242: access to non-existent key in JSON object

**Comment by UndarkAido** [comment]
Are you checking the `bool` argument of `onRead`? It could be an issue on your end, especially since you didn't give me the entire output.

**Comment by niansa** [comment]
Seems like it fixed itself
